export const AllProductsData = [
    {
        id:'st1',
        title:'My pencil (Wow) Dollar 12 pieces',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:210,
        imageURL:'/images/my_pencil_dollar.jpg',
        category:'',
        section:'',
    },
    {
        id:'st2',
        title:'Apple Sharpner',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:0,
        imageURL:'/images/apple_sharpener.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st3',
        title:'Board Marker Dollar 12 pieces',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:680,
        imageURL:'/images/board_marker.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st4',
        title:'Cutter',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:305,
        imageURL:'/images/cutter.jpg',
        category:'',
        section:'',
    },
    {
        id:'st5',
        title:'Deer Color Large 12 pieces',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:110,
        imageURL:'/images/deer_color_large.jpg',
        category:'',
        section:'',
    },
    {
        id:'st6',
        title:'Deer Color Small 12 pieces',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:65,
        imageURL:'/images/deer_color_small.jpg',
        category:'',
        section:'',
    },
    {
        id:'st7',
        title:'Dollar Cliper + BP1 Pen 10 pieces',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:140,
        imageURL:'/images/dollar_clipper.jpg',
        category:'',
        section:'',
    },
    {
        id:'st8',
        title:'Dollar Pointer 10 pieces',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:245,
        imageURL:'/images/dollar_pointer.jpg',
        category:'',
        section:'',
    },
    {
        id:'st9',
        title:'Dollar Jet Flow Ball Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:355,
        imageURL:'/images/dollar_jet_flow.jpg',
        category:'',
        section:'',
    },
    {
        id:'st10',
        title:'4 color ball pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:0,
        imageURL:'/images/today/4color_ballpen.jpg',
        category:'',
        section:'',
    },
    {
        id:'st11',
        title:"L'il Bin Pencil sharpener 24-pieces",
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:345,
        imageURL:'/images/today/bin_sharpener.jpg',
        category:'',
        section:'',
    },
    {
        id:'st12',
        title:'China Clay 12-pieces',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:75,
        imageURL:'/images/today/china_clay.jpg',
        category:'',
        section:'',
    },
    {
        id:'st13',
        title:'China Envelope',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:150,
        imageURL:'/images/today/china_envelope.jpg',
        category:'',
        section:'',
    },
    {
        id:'st13a',
        title:'Simple Envelope',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:100,
        imageURL:'/images/today/china_envelope.jpg',
        category:'',
        section:'',
    },
    {
        id:'st14',
        title:'China Fan Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:26,
        imageURL:'/images/today/china_pencil_fan.jpg',
        category:'',
        section:'',
    },
    {
        id:'st15',
        title:'China Game Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:43,
        imageURL:'/images/today/china_pencil_game.jpg',
        category:'',
        section:'',
    },
    {
        id:'st16',
        title:'China Whistle Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:26,
        imageURL:'/images/today/china_pencil_whistle.jpg',
        category:'',
        section:'',
    },
    {
        id:'st17',
        title:'Dux correction pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:525,
        imageURL:'/images/today/dux_correction_pen.jpg',
        category:'',
        section:'',
    },
    {
        id:'st18',
        title:'Dux Stapler D12',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:420,
        imageURL:'/images/today/dux_stapler_d12.jpg',
        category:'',
        section:'',
    },
    {
        id:'st19',
        title:'Goldfish Colors (Large)',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:195,
        imageURL:'/images/today/goldfish_colors_large.jpg',
        category:'',
        section:'',
    },
    {
        id:'st20',
        title:'Goldfish Colors (small)',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:110,
        imageURL:'/images/today/goldfish_colors_small.jpg',
        category:'',
        section:'',
    },
    {
        id:'st21',
        title:'Goldfish Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:185,
        imageURL:'/images/today/goldfish_pencil.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st22',
        title:'Ink Remover',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:230,
        imageURL:'/images/today/ink_remover.jpg',
        category:'',
        section:'',
    },
    {
        id:'st23',
        title:'Invisible Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:36,
        imageURL:'/images/today/invisible_pen.jpg',
        category:'',
        section:'',
    },
    {
        id:'st24',
        title:'Mercury Fiber Color',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:95,
        imageURL:'/images/today/mercury_fiber_color.jpg',
        category:'',
        section:'',
    },
    {
        id:'st25',
        title:'Mercury Pencil 8120',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:705,
        imageURL:'/images/today/mercury_pencil.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st26',
        title:'Rocky Sharpener 50 Pcs',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:300,
        imageURL:'/images/today/rocky_sharpener.png',
        category:'',
        section:'',
    },
    {
        id:'st27',
        title:'Sticky Notes',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:72,
        imageURL:'/images/today/sticky_notes.jpg',
        category:'',
        section:'',
    },
    {
        id:'st28',
        title:'Dux Eraser',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:405,
        imageURL:'/images/dux_eraser.jpg',
        category:'',
        section:'',
    },
    {
        id:'st29',
        title:'Glue Stick Deer',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:430,
        imageURL:'/images/glue_stick_deer.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st30',
        title:'GMSA',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:185,
        imageURL:'/images/gmsa.jpg',
        category:'',
        section:'',
    },
    {
        id:'st31',
        title:'Mercury Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/mercury_pencil.jpg',
        category:'',
        section:'',
    },
    {
        id:'st32',
        title:'My Pencil Color 24',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:285,
        imageURL:'/images/my_pencil_color.jpg',
        category:'',
        section:'',
    },
    {
        id:'st33',
        title:'My Pencil Color 12',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:250,
        imageURL:'/images/my_pencil_color12.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st34',
        title:'Permanent Marker',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:680,
        imageURL:'/images/permanent_marker.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st35',
        title:'Piano Sharpener',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:300,
        imageURL:'/images/piano_sharpener.png',
        category:'',
        section:'',
    },
    {
        id:'st36',
        title:'Katoon Sharpener 44 pcs',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:0,
        imageURL:'/images/katoon_sharpener.png',
        category:'',
        section:'',
    },
    {
        id:'st37',
        title:'Signature Ball Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/signature_ball_pen.png',
        category:'',
        section:'',
    },
    {
        id:'st38',
        title:'Stamp Pad',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:600,
        imageURL:'/images/stamp_pad.jpg',
        category:'',
        section:'',
    },
    {
        id:'st39',
        title:'Steel Scale 12-inch',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:50,
        imageURL:'/images/steel_scale_12inch.jpg',
        category:'',
        section:'',
    },
    {
        id:'st40',
        title:'7i7 Ink Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:570,
        imageURL:'/images/tuesday/7i7_ink_pen.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st41',
        title:'Bahadur Eraser',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:100,
        imageURL:'/images/tuesday/bahadur_eraser.jpg',
        category:'',
        section:'',
    },
    {
        id:'st42',
        title:'Brito Color Large',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:190,
        imageURL:'/images/tuesday/brito_color_large.PNG',
        category:'',
        section:'',
    },
    {
        id:'st43',
        title:'Brito Color Small',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:110,
        imageURL:'/images/tuesday/BritoColorSmall.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st44',
        title:'Protractor (D scale)',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:130,
        imageURL:'/images/tuesday/protractor.png',
        category:'',
        section:'',
    },
    {
        id:'st45',
        title:'Deer Wonder Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:170,
        imageURL:'/images/tuesday/DeerWonderPencil.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st46',
        title:'Dollar Ink 12 Pcs',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:400,
        imageURL:'/images/tuesday/dollar_ink.jpg',
        category:'',
        section:'',
    },
    {
        id:'st47',
        title:'Highlighter Neon',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:850,
        imageURL:'/images/tuesday/highlighter_neon.jpg',
        category:'',
        section:'',
    },
    {
        id:'st48',
        title:'Murcury Urdu Marker',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:95,
        imageURL:'/images/tuesday/MurcuryUrduMarker.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st49',
        title:'Tape Osaka',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:425,
        imageURL:'/images/tuesday/OSAKATape.jpg',
        category:'',
        section:'',
    },
    {
        id:'st50',
        title:'Piano A-star Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:430,
        imageURL:'/images/tuesday/piano_A_star_pen.jpg',
        category:'',
        section:'',
    },
    {
        id:'st51',
        title:'Piano Fountain Ink Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:0,
        imageURL:'/images/tuesday/piano_fountain_ink_pen.jpg',
        category:'',
        section:'',
    },
    {
        id:'st52',
        title:'Piano G5 Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:110,
        imageURL:'/images/tuesday/piano_g5.png',
        category:'',
        section:'',
    },
    {
        id:'st53',
        title:'Piano Pointer',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:205,
        imageURL:'/images/tuesday/PianoPointer.jpg',
        category:'',
        section:'',
    },
    {
        id:'st54',
        title:'Scotch Tape 1 inch',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:0,
        imageURL:'/images/tuesday/scotch_tap_1inch.jpg',
        category:'',
        section:'',
    },
    {
        id:'st55',
        title:'Scotch Tape 2 inch',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:0,
        imageURL:'/images/tuesday/scotch_tap_2inch.jpg',
        category:'',
        section:'',
    },
    {
        id:'st56',
        title:'Scotch Tape small',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:70,
        imageURL:'/images/tuesday/scotch_tap_rs10.jpg',
        category:'',
        section:'',
    },
    {
        id:'st57',
        title:'SP-10 Ink Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:510,
        imageURL:'/images/tuesday/sp10_ink_pen.jpg',
        category:'',
        section:'',
    },
    {
        id:'st58',
        title:'Staple Pin Dollar #10',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:440,
        imageURL:'/images/tuesday/staple_pin_dollar_10.jpg',
        category:'',
        section:'',
    },
    {
        id:'st59',
        title:'Staple Pin Dux #10',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:0,
        imageURL:'/images/tuesday/staple_pin_dux_10.jpg',
        category:'',
        section:'',
    },
    {
        id:'st60',
        title:'TipTop Glue',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:245,
        imageURL:'/images/tuesday/tip_top_glue.png',
        category:'',
        section:'',
    },
    {
        id:'st61',
        title:'UHU',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:415,
        imageURL:'/images/tuesday/UHU.jpg',
        category:'',
        section:'',
    },
    {
        id:'st62',
        title:'Party Balloon 100 Pcs',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:320,
        imageURL:'/images/wednesday/party_baloon.jpg',
        category:'',
        section:'',
    },
    {
        id:'st62a',
        title:'Party Balloon 100 Pcs',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:550,
        imageURL:'/images/wednesday/party_balloons2.png',
        category:'',
        section:'',
    },
    {
        id:'st63',
        title:'Birthday Balloons 100 Pcs',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:300,
        imageURL:'/images/wednesday/ballons_100pcs.jpg',
        category:'',
        section:'',
    },
    {
        id:'st64',
        title:'Sim Sim Ball (Small)',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:200,
        imageURL:'/images/sim_sim_ball.jpg',
        category:'',
        section:'',
    },
    {
        id:'st65',
        title:'Sim Sim Ball (Medium)',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:250,
        imageURL:'/images/sim_sim_ball.jpg',
        category:'',
        section:'',
    },
    {
        id:'st66',
        title:'Sim Sim Ball (Large)',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:450,
        imageURL:'/images/sim_sim_ball.jpg',
        category:'',
        section:'',
    },
      
]