export const AllProductsData = [
    {
        id:'st1',
        title:'My pencil (Wow) Dollor',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:210,
        imageURL:'/images/my_pencil_dollar.jpg',
        category:'',
        section:'',
    },
    {
        id:'st2',
        title:'Apple Sharpner',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/apple_sharpener.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st3',
        title:'Board Marker Dollar',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/board_marker.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st4',
        title:'Cutter',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/cutter.jpg',
        category:'',
        section:'',
    },
    {
        id:'st5',
        title:'Deer Color Large',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/deer_color_large.jpg',
        category:'',
        section:'',
    },
    {
        id:'st6',
        title:'Deer Color Small',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/deer_half_color.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st7',
        title:'Dollar Cliper + BP1 Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/dollar_clipper.jpg',
        category:'',
        section:'',
    },
    {
        id:'st8',
        title:'Dollar Pointer',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/dollar_pointer.jpg',
        category:'',
        section:'',
    },
    {
        id:'st9',
        title:'Dollar Jet Flow Ball Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/dollar_jet_flow.jpg',
        category:'',
        section:'',
    },
    {
        id:'st2',
        title:'Apple Sharpner',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/apple_sharpener.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st2',
        title:'Apple Sharpner',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/apple_sharpener.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st2',
        title:'Apple Sharpner',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/apple_sharpener.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st2',
        title:'Apple Sharpner',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/apple_sharpener.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st2',
        title:'Apple Sharpner',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/apple_sharpener.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st2',
        title:'Apple Sharpner',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/apple_sharpener.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st2',
        title:'Apple Sharpner',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/apple_sharpener.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st2',
        title:'Apple Sharpner',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/apple_sharpener.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st2',
        title:'Apple Sharpner',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/apple_sharpener.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st2',
        title:'Apple Sharpner',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/apple_sharpener.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st2',
        title:'Apple Sharpner',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/apple_sharpener.jpeg',
        category:'',
        section:'',
    },
    
    
]