export const AllProductsData = [
    {
        id:'st1',
        title:'My pencil (Wow) Dollor',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:210,
        imageURL:'/images/my_pencil_dollar.jpg',
        category:'',
        section:'',
    },
    {
        id:'st2',
        title:'Apple Sharpner',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/apple_sharpener.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st3',
        title:'Board Marker Dollar',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/board_marker.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st4',
        title:'Cutter',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/cutter.jpg',
        category:'',
        section:'',
    },
    {
        id:'st5',
        title:'Deer Color Large',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/deer_color_large.jpg',
        category:'',
        section:'',
    },
    {
        id:'st6',
        title:'Deer Color Small',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/deer_half_color.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st7',
        title:'Dollar Cliper + BP1 Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/dollar_clipper.jpg',
        category:'',
        section:'',
    },
    {
        id:'st8',
        title:'Dollar Pointer',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/dollar_pointer.jpg',
        category:'',
        section:'',
    },
    {
        id:'st9',
        title:'Dollar Jet Flow Ball Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/dollar_jet_flow.jpg',
        category:'',
        section:'',
    },
    {
        id:'st10',
        title:'4 color ball pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/4color_ballpen.jpg',
        category:'',
        section:'',
    },
    {
        id:'st11',
        title:'Bin sharpener',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/bin_sharpener.jpg',
        category:'',
        section:'',
    },
    {
        id:'st12',
        title:'China Clay',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/china_clay.jpg',
        category:'',
        section:'',
    },
    {
        id:'st13',
        title:'China Envelope',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/china_envelop.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st14',
        title:'China Fan Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/china_pencil_fan.jpg',
        category:'',
        section:'',
    },
    {
        id:'st15',
        title:'China Game Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/china_pencil_game.jpg',
        category:'',
        section:'',
    },
    {
        id:'st16',
        title:'China Whistle Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/china_pencil_whistle.jpg',
        category:'',
        section:'',
    },
    {
        id:'st17',
        title:'Dux correction pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/dux_correction_pen.jpg',
        category:'',
        section:'',
    },
    {
        id:'st18',
        title:'Dux Stapler D12',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/dux_stapler_d12.jpg',
        category:'',
        section:'',
    },
    {
        id:'st19',
        title:'Goldfish Colors (Large)',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/goldfish_colors_large.jpg',
        category:'',
        section:'',
    },
    {
        id:'st20',
        title:'Goldfish Colors (small)',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/goldfish_colors_small.jpg',
        category:'',
        section:'',
    },
    {
        id:'st21',
        title:'Goldfish Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/goldfish_pencil.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st22',
        title:'Ink Remover',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/ink_remover.jpg',
        category:'',
        section:'',
    },
    {
        id:'st23',
        title:'Invisible Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/invisible_pen.jpg',
        category:'',
        section:'',
    },
    {
        id:'st24',
        title:'Mercury Fiber Color',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/mercury_fiber_color.jpg',
        category:'',
        section:'',
    },
    {
        id:'st25',
        title:'Mercury Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/mercury_pencil.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st26',
        title:'Rocky Sharpener',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/rocky_sharpener.jpeg',
        category:'',
        section:'',
    },
    {
        id:'st27',
        title:'Sticky Notes',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/today/sticky_notes.jpg',
        category:'',
        section:'',
    }

    
    
    
]